### ISSUE TITLE
色がどぎつい

### ISSUE THREAD

**Issue by sktom** [sktom/Reasons#1]
原色をそのまま使うのはやめよう
薄くて控えめな色を選んでほしい

**Comment by sktom** [comment]
具体例な利用例が欲しい

デモ用のサーバーを用意してもよいかも

**Comment by sktom** [comment]
少し手直ししました

**Comment by laspel** [comment]
良くなった・・・が、今度は寝ぼけてきた。

**Comment by sktom** [comment]
少しはっきりさせてみた

**Comment by laspel** [comment]
とりあえず、色はこのくらいで良いのではないかと。あくまで「当面」だが。
